%define bamboo_home %{_var}/lib/bamboo/home
%define bamboo_tomcat %{_var}/lib/bamboo/tomcat
%define confdir %{bamboo_tomcat}/conf
%define workdir %{bamboo_tomcat}/work
%define tmpdir %{bamboo_tomcat}/tmp
%define logdir %{bamboo_tomcat}/log

Name: tomcat-bamboo
Version: 3.2.2

Summary: Atlassian Bamboo Tomcat Profile
Release: 1
Source0: apache-tomcat-6.0.33.tar.gz
Source1: atlassian-bamboo-3.2.2.war
Url: http://www.atlassian.com/software/bamboo/
Group: System Environment/Daemons

License: Proprietary

BuildArch: noarch

%description
Bamboo is a turnkey application that automates your build, test and deployment processes.

Authors:
--------
    Mark Wolfe <mark@wolfe.id.au>

%prep
%setup -q -n apache-tomcat-6.0.33

%build
# remove all the files already in base.
for i in bin lib LICENSE NOTICE RELEASE-NOTES RUNNING.txt
do
  %{__rm} -R $i
done

# don't need anything out of webapps
%{__rm} -r webapps

%install
%{__rm} -rf $RPM_BUILD_ROOT
%{__mkdir} -p ${RPM_BUILD_ROOT}%{bamboo_tomcat}/bamboo
%{__mkdir} -p ${RPM_BUILD_ROOT}%{bamboo_home}
%{__cp} -v -p -R conf ${RPM_BUILD_ROOT}%{confdir}
%{__install} -d -m 0755 ${RPM_BUILD_ROOT}%{confdir}/Catalina/localhost
%{__install} -d -m 0775 ${RPM_BUILD_ROOT}%{logdir}
/bin/touch ${RPM_BUILD_ROOT}%{logdir}/catalina.out
%{__install} -d -m 0775 ${RPM_BUILD_ROOT}%{workdir}
%{__install} -d -m 0775 ${RPM_BUILD_ROOT}%{tmpdir}
/usr/bin/unzip "%{SOURCE1}" -d %{buildroot}%{bamboo_tomcat}/bamboo

%clean
%{__rm} -rf %{buildroot}

%pre
%{_sbindir}/groupadd -r bamboo &>/dev/null || :
%{_sbindir}/useradd -g bamboo -s /bin/false -r -c "Bamboo Continuous Build server" -d "%{buildroot}%{bamboo_home}" bamboo &>/dev/null || :

%files
%defattr(-,root,root,-)
%attr(0775,root,tomcat) %dir %{confdir}
%attr(0775,root, tomcat) %{confdir}/Catalina
# %dir %{confdir}/Catalina
#%attr(0775,root,tomcat) %dir %{confdir}/Catalina/localhost
%config(noreplace) %{confdir}/*.policy
%config(noreplace) %{confdir}/*.properties
%config(noreplace) %{confdir}/context.xml
%config(noreplace) %{confdir}/server.xml
%attr(0664,root,tomcat) %config(noreplace) %{confdir}/tomcat-users.xml
%config(noreplace) %{confdir}/web.xml
%attr(0775,root,tomcat) %dir %{logdir}
%attr(0644,tomcat,tomcat) %{logdir}/catalina.out
%attr(0775,root,tomcat) %dir %{tmpdir}
%attr(0775,root,tomcat) %dir %{workdir}
%attr(0775,root,tomcat) %dir %{bamboo_tomcat}/bamboo
%defattr(0644,root,tomcat,0755)
/var/lib/bamboo/tomcat/bamboo/buildResult/viewCommitsSummary.ftl
/var/lib/bamboo/tomcat/bamboo/buildResult/viewCommentsSummary.ftl
/var/lib/bamboo/tomcat/bamboo/project/viewProject.ftl
/var/lib/bamboo/tomcat/bamboo/myBambooDashboard.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/viewJiraIssuesForPlan.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/viewBuildResultsByJiraIssues.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/viewJiraIssuesSummaryForBuildResult.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/viewPlansByJiraIssues.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/viewJiraIssueComponents.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/addJiraIssueToBuildResult.ftl
/var/lib/bamboo/tomcat/bamboo/plugins/jira-plugin/viewJiraIssuesForBuildResult.ftl
/var/lib/bamboo/tomcat/bamboo/labels/viewLabels.ftl
/var/lib/bamboo/tomcat/bamboo/labels/viewBuildsForLabel.ftl
/var/lib/bamboo/tomcat/bamboo/agentServer/fingerprint.ftl
/var/lib/bamboo/tomcat/bamboo/agentServer/BambooAgent.jnlp.ftl
/var/lib/bamboo/tomcat/bamboo/start.action
/var/lib/bamboo/tomcat/bamboo/viewBuildSummary.ftl
/var/lib/bamboo/tomcat/bamboo/licenses/jta-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/junit-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jaxen-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/webwork-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/xml-apis-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-beanutils-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/lucene-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/hibernate-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-lang-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdk-5.0u17-dlj-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/p6spy-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-lang-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-seraph-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/joda-time-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/mockobjects-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/rome-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/cglib-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-collections-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/smackx-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jcip-annotations-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-io-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/msv-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/lucene-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdom-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-event-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/isorelax-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/sitemesh-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-plugins-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/log4j-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-beanutils-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-mail-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-core-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/tm-extractors-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/osuser-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/pdfbox-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-logging-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/xercesImpl-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/alt-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/asm-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdk-6u12-dlj-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/aopalliance-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-config-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/ldaptemplate-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/servlet-api-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/acegi-security-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/oscore-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/poi-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/odmg-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-user-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdk-6u12-dlj-THIRDPARTYLICENSEREADME.html
/var/lib/bamboo/tomcat/bamboo/licenses/commons-codec-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/xmlrpc-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/hsqldb-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-johnson-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-io-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/ehcache-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/p6spy-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/backport-util-concurrent-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/xmlParserAPIs-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/oro-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-profiling-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/ant-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/ant-NOTICE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdk-6u12-dlj-README.html
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-velocity-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/joda-time-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-spring-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/aspectwerkz-core-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-bonnie-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/dom4j-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/acegi-security-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/ognl-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/spring-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/quartz-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/saxpath-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/velocity-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/relaxngDatatype-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-digester-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/smack-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/mail-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/annotations-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jmock-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/asm-util-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/propertyset-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/atlassian-bucket-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/commons-logging-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdk-5.0u17-dlj-README.html
/var/lib/bamboo/tomcat/bamboo/licenses/commons-collections-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/xwork-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/jdk-5.0u17-dlj-THIRDPARTYLICENSEREADME.txt
/var/lib/bamboo/tomcat/bamboo/licenses/rife-continuations-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/licenses/oscache-LICENSE.txt
/var/lib/bamboo/tomcat/bamboo/forgotPassword.ftl
/var/lib/bamboo/tomcat/bamboo/sendingNewPassword.ftl
/var/lib/bamboo/tomcat/bamboo/reports/viewReport.ftl
/var/lib/bamboo/tomcat/bamboo/reports/viewReportHideHeader.ftl
/var/lib/bamboo/tomcat/bamboo/currentActivityDashboard.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/project/selectCreateProject.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/errorAjaxRefresh.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/actionErrors.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/labels/labels.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/labels/favouriteIndicator.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/labels/labelInput.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/labels/labelPicker.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/labels/labelView.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/listBuilds.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/jsBuildSummaryAll.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/adminMenu.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/buildResultsNavigator.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/showBuildQueue.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/variable/variables.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/systemProperties.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/buildResults/displayAuthorBuildsTable.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/buildResults/buildResultsTableByPlans.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/buildResults/buildResultsTable.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/buildResults/showBuildResultsTable.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/editArtifactSubscription.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/addArtifactSubscription.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/editArtifactDefinition.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/confirmMoveJob.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/confirmDeleteArtifactSubscription.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/confirmMoveStage.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/confirmDeleteArtifactDefinition.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/renameArtifactDefinitionToEnableSharing.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/artifacts.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/confirmRemoveAllArtifacts.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/confirmToggleSharedArtifact.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/artifact/addArtifactDefinition.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/user/favourites.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/user/responsibilities.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/user/breakages.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/user/changes.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/navigationMenu.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/chains/editChainKeyName.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/chains/selectCreateStage.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/displayBuildSummariesBrief.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/displayBuildSummaries.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/displayPlanSummary.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/planPermissionTable.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/displayBuildPlansList.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/displayWideBuildPlansList.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/editJobKeyName.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/plan/latestStatus.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/jsBuildSummaryFavourites.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/charts/combinedByBuildNumberChart.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/charts/jsCombinedByTimePeriodChart.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/charts/reportChart.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/charts/combinedByTimePeriodChart.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/startupWelcome.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/current/activityLogs.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/showAdminErrors.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/breadCrumbs.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/showSystemErrors.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/minimalFooter.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/setupHeader.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/header.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/htmlHeader.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/setupFooter.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/footer.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/decorator/bambooBanner.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/statistics/recentFailures.ftl
/var/lib/bamboo/tomcat/bamboo/fragments/statistics/successRatio.ftl
/var/lib/bamboo/tomcat/bamboo/activityStream.ftl
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/perforce-triggers/postCommitBuildTrigger.py
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/perforce-triggers/postCommitBuildTrigger.sh
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/cvs-triggers/postCommitBuildTrigger.sh
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/cvs-triggers/preCommit.sh
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/jsvn.bat
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/lib/svnkit-cli-1.2.1.5297.jar
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/lib/logging.properties.disabled
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/lib/svnkit-1.2.1.5297.jar
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/svn-triggers/postCommitBuildTrigger.py
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/svn-triggers/postCommitBuildTrigger.sh
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/jsvn
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/maven2/deploy.pl
/var/lib/bamboo/tomcat/bamboo/repositoryScripts/maven2/cleanRepo.pl
/var/lib/bamboo/tomcat/bamboo/META-INF/MANIFEST.MF
/var/lib/bamboo/tomcat/bamboo/META-INF/maven/com.atlassian.bamboo/atlassian-bamboo-web-app/pom.properties
/var/lib/bamboo/tomcat/bamboo/META-INF/maven/com.atlassian.bamboo/atlassian-bamboo-web-app/pom.xml
/var/lib/bamboo/tomcat/bamboo/func/obj.js
/var/lib/bamboo/tomcat/bamboo/func/func.js
/var/lib/bamboo/tomcat/bamboo/func/func.ftl
/var/lib/bamboo/tomcat/bamboo/func/func.css
/var/lib/bamboo/tomcat/bamboo/admin/viewGlobalAuditLog.ftl
/var/lib/bamboo/tomcat/bamboo/admin/deleteBuildsConfirmation.ftl
/var/lib/bamboo/tomcat/bamboo/admin/systemInfo.ftl
/var/lib/bamboo/tomcat/bamboo/admin/system/viewAllRepositories.ftl
/var/lib/bamboo/tomcat/bamboo/admin/system/viewBambooInternals.ftl
/var/lib/bamboo/tomcat/bamboo/admin/viewConfigureSecurity.ftl
/var/lib/bamboo/tomcat/bamboo/admin/databaseConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/admin/importConfirmation.ftl
/var/lib/bamboo/tomcat/bamboo/admin/configureLog4j.ftl
/var/lib/bamboo/tomcat/bamboo/admin/configureGlobalVariables.ftl
/var/lib/bamboo/tomcat/bamboo/admin/changePassword.ftl
/var/lib/bamboo/tomcat/bamboo/admin/updateLicense.ftl
/var/lib/bamboo/tomcat/bamboo/admin/repository/viewPerforceManager.ftl
/var/lib/bamboo/tomcat/bamboo/admin/systemErrors.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/listElasticImageConfigurations.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/listActiveInstancesForConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/disableElasticImageConfigurationConfirmation.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/viewElasticImageConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/editElasticImageConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/deleteElasticImageConfigurationConfirmation.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/image/configuration/shutdownElasticInstanceForConfigurationConfirm.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/viewElasticAgentHistory.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/viewConfigureElasticCloud.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/commonElasticFunctions.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/shutdownElasticInstance.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/viewElasticInstanceSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/elasticSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/schedule/viewElasticInstanceSchedules.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/schedule/confirmDeleteElasticInstanceSchedule.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/schedule/editElasticInstanceSchedule.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/editElasticCapability.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/confirmDisableElasticConfig.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/viewElasticInstance.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/editConfigureElasticCloud.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/manageElasticInstances.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/createElasticInstances.ftl
/var/lib/bamboo/tomcat/bamboo/admin/elastic/allElasticInstances.ftl
/var/lib/bamboo/tomcat/bamboo/admin/configureSecurity.ftl
/var/lib/bamboo/tomcat/bamboo/admin/import.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/viewBuildExpiry.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/viewBuildExpiryFragment.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/editParameterisedManualBuild.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/monitoring/editBuildHangingDetection.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/monitoring/viewBuildHangingDetection.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/editBuildExpiryForm.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/editBuildExpiry.ftl
/var/lib/bamboo/tomcat/bamboo/admin/build/viewAvailableVariables.ftl
/var/lib/bamboo/tomcat/bamboo/admin/backups/viewBackups.ftl
/var/lib/bamboo/tomcat/bamboo/admin/backups/configureBackups.ftl
/var/lib/bamboo/tomcat/bamboo/admin/gadgets/viewGadgetUrls.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/editCapability.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/remoteAgentsLogSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/editCapabilityKey.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/atlassian-bamboo-agent-installer-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/admin/agent/addRemoteAgent.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewCapabilityKeySnippet.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/renameCapabilityNotAllowed.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewOfflineElasticAgentDetails.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewAgents.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewAgent.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewCapabilityKeyMacro.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/addCapabilityFragment.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/configureSharedCapabilities.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/bamboo-agent-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/admin/agent/configureAgentCapability.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewAgentPlanMatrix.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewCapabilitiesByType.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/disableRemoteAgentFunction.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/addAgent.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewCapabilityKey.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/editAgent.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/viewAgentDetailsSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/renameConfirmation.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/offlineRemoteAgentSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/admin/agent/renameCapability.ftl
/var/lib/bamboo/tomcat/bamboo/admin/administer.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/userPicker.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/userPickerForm.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/configureUser.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/userNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/viewUserSummary.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/viewAdministrators.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/viewUsers.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/viewPaginatedUsers.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/userPickerResults.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/changeProfile.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/editUserNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/userProfile.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/viewSearchUsers.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/configureAlias.ftl
/var/lib/bamboo/tomcat/bamboo/admin/user/signupUser.ftl
/var/lib/bamboo/tomcat/bamboo/admin/viewError.ftl
/var/lib/bamboo/tomcat/bamboo/admin/viewGlobalPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/admin/editConcurrentBuildConfig.ftl
/var/lib/bamboo/tomcat/bamboo/admin/schedule/cronEditor.ftl
/var/lib/bamboo/tomcat/bamboo/admin/notification/updateSystemNotification.ftl
/var/lib/bamboo/tomcat/bamboo/admin/notification/viewSystemNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/admin/group/viewPaginatedGroups.ftl
/var/lib/bamboo/tomcat/bamboo/admin/group/viewGroups.ftl
/var/lib/bamboo/tomcat/bamboo/admin/group/configureGroup.ftl
/var/lib/bamboo/tomcat/bamboo/admin/instantmessagingserver/viewInstantMessagingServer.ftl
/var/lib/bamboo/tomcat/bamboo/admin/instantmessagingserver/configureInstantMessagingServerFragment.ftl
/var/lib/bamboo/tomcat/bamboo/admin/instantmessagingserver/configureInstantMessagingServer.ftl
/var/lib/bamboo/tomcat/bamboo/admin/instantmessagingserver/viewInstantMessagingServers.ftl
/var/lib/bamboo/tomcat/bamboo/admin/passwordChangeSuccessful.ftl
/var/lib/bamboo/tomcat/bamboo/admin/deleteBuilds.ftl
/var/lib/bamboo/tomcat/bamboo/admin/manageCaches.ftl
/var/lib/bamboo/tomcat/bamboo/admin/userManagement.ftl
/var/lib/bamboo/tomcat/bamboo/admin/viewConcurrentBuildConfig.ftl
/var/lib/bamboo/tomcat/bamboo/admin/mail/viewMailServer.ftl
/var/lib/bamboo/tomcat/bamboo/admin/mail/configureMailServerFragment.ftl
/var/lib/bamboo/tomcat/bamboo/admin/mail/configureMailServer.ftl
/var/lib/bamboo/tomcat/bamboo/admin/index/reindex.ftl
/var/lib/bamboo/tomcat/bamboo/admin/export.ftl
/var/lib/bamboo/tomcat/bamboo/admin/changeForgottenPassword.ftl
/var/lib/bamboo/tomcat/bamboo/admin/bulk/confirmBulkAction.ftl
/var/lib/bamboo/tomcat/bamboo/admin/bulk/choosePlansForBulkAction.ftl
/var/lib/bamboo/tomcat/bamboo/admin/bulk/resultOfBulkAction.ftl
/var/lib/bamboo/tomcat/bamboo/admin/bulk/inputFormForBulkAction.ftl
/var/lib/bamboo/tomcat/bamboo/admin/bulk/viewAvailableBulkAction.ftl
/var/lib/bamboo/tomcat/bamboo/admin/configureGlobalPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/admin/generalConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/admin/maven/confirmImportWithMaven.ftl
/var/lib/bamboo/tomcat/bamboo/admin/maven/configureImportWithMaven.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/userBuilds.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/response.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/recentlyCompletedBuildResultsForBuild.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/logToServer.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/listProjects.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/listBuilds.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/buildResultsDetails.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/latestBuildResults.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/latestBuildsByUser.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/listRunningInstances.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/accessDenied.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/macros.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/error.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/login.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/updateAndBuild.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/latestBuildResultsForProject.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/recentlyCompletedBuildResultsForProject.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/projectDetails.ftl
/var/lib/bamboo/tomcat/bamboo/api/rest/bambooBuildNumber.ftl
/var/lib/bamboo/tomcat/bamboo/lib/components.ftl
/var/lib/bamboo/tomcat/bamboo/lib/resultSummary.ftl
/var/lib/bamboo/tomcat/bamboo/lib/dojo.ftl
/var/lib/bamboo/tomcat/bamboo/lib/menus.ftl
/var/lib/bamboo/tomcat/bamboo/lib/chains.ftl
/var/lib/bamboo/tomcat/bamboo/lib/build.ftl
/var/lib/bamboo/tomcat/bamboo/lib/tests.ftl
/var/lib/bamboo/tomcat/bamboo/wait.ftl
/var/lib/bamboo/tomcat/bamboo/telemetry.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildBuilder.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildRequirement.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildHangingDetection.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildConfigurationCommon.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/describeAgentAvailability.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editCvsModuleSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editSvnCredentialsSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editSvnUrlSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/configureBuildVariables.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editCvsRootCredentialsSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildTaskSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildRepository.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildTasksCommon.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildTaskInvalid.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editWebUrlSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildArtifact.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/showAgentNumbers.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editManualBuildSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildDetails.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildNotificationSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildTasks.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildNotification.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/changeBuildNotification.ftl
/var/lib/bamboo/tomcat/bamboo/build/edit/editBuildMiscellaneousOptions.ftl
/var/lib/bamboo/tomcat/bamboo/build/expiry/viewBuildExpiryForPlan.ftl
/var/lib/bamboo/tomcat/bamboo/build/expiry/editBuildExpiryForPlan.ftl
/var/lib/bamboo/tomcat/bamboo/build/move/chooseKeysForMove.ftl
/var/lib/bamboo/tomcat/bamboo/build/move/chooseBuildsToMove.ftl
/var/lib/bamboo/tomcat/bamboo/build/move/resultOfPlanMove.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/commonRepositoryEdit.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/addJdkCapabilityFragment.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/configureBuildStrategy.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/configureBuilder.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/configureChangeDetectionRepository.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/addBuilderCapabilityFragment.ftl
/var/lib/bamboo/tomcat/bamboo/build/common/configureRepository.ftl
/var/lib/bamboo/tomcat/bamboo/build/viewRunningPlans.ftl
/var/lib/bamboo/tomcat/bamboo/build/concurrent/viewConcurrentBuildsConfigForPlan.ftl
/var/lib/bamboo/tomcat/bamboo/build/concurrent/editConcurrentBuildsConfigForPlan.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedSvnUrl.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewRepository.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/buildConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedWebUrl.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewTasks.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewBuildHangingDetection.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewBulkBuildResult.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewBuildPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedSvnCredentials.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewDependencies.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/confirmDeleteBuildTaskSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewSvnUrl.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewTaskTypesSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewCurrentBulkBuild.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedCvsModule.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedBulkBuild.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewCvsModule.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewCvsRootCredentials.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewSvnCredentials.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewUpdatedCvsRootCredentials.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/confirmDeleteAllNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewWebUrl.ftl
/var/lib/bamboo/tomcat/bamboo/build/view/viewMiscellaneous.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildResults.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildLog.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildResultsSuccessfulTests.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildArtifacts.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildResultsChanges.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildResultsFailedTests.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewBuildResultsMetaData.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewTestClassResult.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewTestCaseResult.ftl
/var/lib/bamboo/tomcat/bamboo/build/result/viewNoTestCaseResult.ftl
/var/lib/bamboo/tomcat/bamboo/build/tests/viewTestsSummary.ftl
/var/lib/bamboo/tomcat/bamboo/build/tests/viewTestCase.ftl
/var/lib/bamboo/tomcat/bamboo/build/bulkEditPermissions/confirmBulkEditPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/build/bulkEditPermissions/chooseBuildsToBulkEditPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/build/bulkEditPermissions/specifyBulkEditPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/build/add/planLimitReached.ftl
/var/lib/bamboo/tomcat/bamboo/build/add/createChainTasks.ftl
/var/lib/bamboo/tomcat/bamboo/build/add/creationMethodSelection.ftl
/var/lib/bamboo/tomcat/bamboo/build/add/cloneChain.ftl
/var/lib/bamboo/tomcat/bamboo/build/add/createChain.ftl
/var/lib/bamboo/tomcat/bamboo/build/viewBuildActivityLog.ftl
/var/lib/bamboo/tomcat/bamboo/build/viewFailurePeriods.ftl
/var/lib/bamboo/tomcat/bamboo/displayCurrentActivity.ftl
/var/lib/bamboo/tomcat/bamboo/images/deleteBuilds.gif
/var/lib/bamboo/tomcat/bamboo/images/cookie.png
/var/lib/bamboo/tomcat/bamboo/images/build_status_top_right.gif
/var/lib/bamboo/tomcat/bamboo/images/percentage_box_top.gif
/var/lib/bamboo/tomcat/bamboo/images/btn_createaplan.gif
/var/lib/bamboo/tomcat/bamboo/images/start_build.gif
/var/lib/bamboo/tomcat/bamboo/images/add_20.png
/var/lib/bamboo/tomcat/bamboo/images/lightbulb_on.gif
/var/lib/bamboo/tomcat/bamboo/images/wizard_arrow.png
/var/lib/bamboo/tomcat/bamboo/images/good.gif
/var/lib/bamboo/tomcat/bamboo/images/question_and_answer.gif
/var/lib/bamboo/tomcat/bamboo/images/working_sub_directory_option.jpg
/var/lib/bamboo/tomcat/bamboo/images/sync.gif
/var/lib/bamboo/tomcat/bamboo/images/tab_on_left.gif
/var/lib/bamboo/tomcat/bamboo/images/gh-icon-sprite.png
/var/lib/bamboo/tomcat/bamboo/images/message_add.gif
/var/lib/bamboo/tomcat/bamboo/images/download_remote_agent_button.png
/var/lib/bamboo/tomcat/bamboo/images/build_log.gif
/var/lib/bamboo/tomcat/bamboo/images/message.gif
/var/lib/bamboo/tomcat/bamboo/images/reload_icon.gif
/var/lib/bamboo/tomcat/bamboo/images/build_status_bottom_left.gif
/var/lib/bamboo/tomcat/bamboo/images/message.png
/var/lib/bamboo/tomcat/bamboo/images/refresh_grey_16.png
/var/lib/bamboo/tomcat/bamboo/images/working_directory_option.jpg
/var/lib/bamboo/tomcat/bamboo/images/import.gif
/var/lib/bamboo/tomcat/bamboo/images/plugin.gif
/var/lib/bamboo/tomcat/bamboo/images/percentage_box_bottom.gif
/var/lib/bamboo/tomcat/bamboo/images/export.gif
/var/lib/bamboo/tomcat/bamboo/images/delete.gif
/var/lib/bamboo/tomcat/bamboo/images/building.gif
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_right_grey.gif
/var/lib/bamboo/tomcat/bamboo/images/blue_tab_on_right.gif
/var/lib/bamboo/tomcat/bamboo/images/move.gif
/var/lib/bamboo/tomcat/bamboo/images/blue_tab_submenu_on_right.gif
/var/lib/bamboo/tomcat/bamboo/images/xchat.gif
/var/lib/bamboo/tomcat/bamboo/images/bad.gif
/var/lib/bamboo/tomcat/bamboo/images/mail_server.gif
/var/lib/bamboo/tomcat/bamboo/images/stop_build.gif
/var/lib/bamboo/tomcat/bamboo/images/icon_collapse_arrow_up.gif
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/plan_successful_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/start_disabled.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/start.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/plan_disabled_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/shared_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/plan_canceled_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/plan_failed_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/job_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/disable_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/queued_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/artifact_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/wallboard_18.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/enable_16.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/stop.png
/var/lib/bamboo/tomcat/bamboo/images/iconsv3/plan_successful_partial_16.png
/var/lib/bamboo/tomcat/bamboo/images/handle-repeatable.gif
/var/lib/bamboo/tomcat/bamboo/images/queue_on.jpg
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_right.gif
/var/lib/bamboo/tomcat/bamboo/images/build_results.gif
/var/lib/bamboo/tomcat/bamboo/images/previous.gif
/var/lib/bamboo/tomcat/bamboo/images/sprite_changeset-plus.png
/var/lib/bamboo/tomcat/bamboo/images/screenshot_01.jpg
/var/lib/bamboo/tomcat/bamboo/images/license.gif
/var/lib/bamboo/tomcat/bamboo/images/icon_plus_minus.gif
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_left_grey.gif
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_left.gif
/var/lib/bamboo/tomcat/bamboo/images/message_add.png
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_first.gif
/var/lib/bamboo/tomcat/bamboo/images/menu_indicator_for_light_backgrounds.gif
/var/lib/bamboo/tomcat/bamboo/images/handle.png
/var/lib/bamboo/tomcat/bamboo/images/build_results_error.gif
/var/lib/bamboo/tomcat/bamboo/images/agent_arrow.gif
/var/lib/bamboo/tomcat/bamboo/images/success_rate_circle.gif
/var/lib/bamboo/tomcat/bamboo/images/stage-separator.gif
/var/lib/bamboo/tomcat/bamboo/images/blue_tab_submenu_on_left.gif
/var/lib/bamboo/tomcat/bamboo/images/icon_collapse_arrow_down.gif
/var/lib/bamboo/tomcat/bamboo/images/BAM-InstallGraphic-LG.png
/var/lib/bamboo/tomcat/bamboo/images/build_status_bottom_right.gif
/var/lib/bamboo/tomcat/bamboo/images/window.png
/var/lib/bamboo/tomcat/bamboo/images/edit_12.png
/var/lib/bamboo/tomcat/bamboo/images/blue_tab_right.gif
/var/lib/bamboo/tomcat/bamboo/images/view.gif
/var/lib/bamboo/tomcat/bamboo/images/menu_indicator_for_light_backgrounds_lighter.gif
/var/lib/bamboo/tomcat/bamboo/images/gadgets/bg.gif
/var/lib/bamboo/tomcat/bamboo/images/gadgets/btn-reload.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/link.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/btn-locked.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/configure.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/up.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/dn.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/bg-gadget.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/oauth-approval.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/btn-unlock.png
/var/lib/bamboo/tomcat/bamboo/images/gadgets/loading_100.gif
/var/lib/bamboo/tomcat/bamboo/images/gadgets/fhbg.gif
/var/lib/bamboo/tomcat/bamboo/images/gadgets/ie/configure.gif
/var/lib/bamboo/tomcat/bamboo/images/gadgets/ie/btn-reload.gif
/var/lib/bamboo/tomcat/bamboo/images/gadgets/loading.gif
/var/lib/bamboo/tomcat/bamboo/images/tools_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icon_globe.gif
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_last_grey.gif
/var/lib/bamboo/tomcat/bamboo/images/delete_files.gif
/var/lib/bamboo/tomcat/bamboo/images/cookie-thanks.png
/var/lib/bamboo/tomcat/bamboo/images/button_bg.png
/var/lib/bamboo/tomcat/bamboo/images/linkext7.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_single.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_plan_passed_dk.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_buildqueued.png
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_disable.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_building.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/24_jira.png
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_log.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_favourites_on.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_fav_on.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn32_elastic_cloud.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_favourites_off.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_plan_failed_dk.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_expand.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_collapse.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_permission_unchecked.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_checkinout.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_plan_cancelled_dk.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/JIRA.ico
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_edit.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_run_disabled.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_stop.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/Thumbs.db
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_run.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_building_dark.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_agent_offline.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_fav_off.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_comment.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_stopping.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/16_jira.png
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_permission_check.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_plan_cancelled.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_agent_online.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_plan_passed.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_cancelbuild.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_enable.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_elastic_cloud.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_plan_failed.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_hourglass.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/icn_delete.gif
/var/lib/bamboo/tomcat/bamboo/images/jt/create_12.png
/var/lib/bamboo/tomcat/bamboo/images/goto.gif
/var/lib/bamboo/tomcat/bamboo/images/clone.gif
/var/lib/bamboo/tomcat/bamboo/images/preferences.gif
/var/lib/bamboo/tomcat/bamboo/images/tab_right.gif
/var/lib/bamboo/tomcat/bamboo/images/job-progress-bar-bg.png
/var/lib/bamboo/tomcat/bamboo/images/bamboo-icon.png
/var/lib/bamboo/tomcat/bamboo/images/BAM-InstallGraphic-SM.png
/var/lib/bamboo/tomcat/bamboo/images/bamboo_header_logo.png
/var/lib/bamboo/tomcat/bamboo/images/save.gif
/var/lib/bamboo/tomcat/bamboo/images/footer.gif
/var/lib/bamboo/tomcat/bamboo/images/folder.gif
/var/lib/bamboo/tomcat/bamboo/images/add.gif
/var/lib/bamboo/tomcat/bamboo/images/tab_on_right.gif
/var/lib/bamboo/tomcat/bamboo/images/tab_left.gif
/var/lib/bamboo/tomcat/bamboo/images/task-type-default.png
/var/lib/bamboo/tomcat/bamboo/images/ss.gif
/var/lib/bamboo/tomcat/bamboo/images/menu_indicator_for_dark_backgrounds.gif
/var/lib/bamboo/tomcat/bamboo/images/icon_collapse_minus.gif
/var/lib/bamboo/tomcat/bamboo/images/system_info.gif
/var/lib/bamboo/tomcat/bamboo/images/warning.gif
/var/lib/bamboo/tomcat/bamboo/images/accept_remote_calls.jpg
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_first_grey.gif
/var/lib/bamboo/tomcat/bamboo/images/agent_arrow_header.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/delete_8_gray.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_first_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/user_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/navigate_close.png
/var/lib/bamboo/tomcat/bamboo/images/icons/wait.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_file.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_up_blue_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_left_small.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_down_blue_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_right_small.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_up_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/label.png
/var/lib/bamboo/tomcat/bamboo/images/icons/bullet_inprogress.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_left_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/gear_forbidden.png
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_last.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/first.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/bullet_done.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/jira_arrow_down.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/businessmen.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/config_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/tools_12.png
/var/lib/bamboo/tomcat/bamboo/images/icons/star_on.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_hourglass.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/bullet_creme.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/jira_arrow_last.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_computer.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_right_small_fade.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/jira_arrow_up.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/trash_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_blockcollapsed.png
/var/lib/bamboo/tomcat/bamboo/images/icons/previous.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/save_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_down_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/unshared.png
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_move_ns.png
/var/lib/bamboo/tomcat/bamboo/images/icons/view_20.png
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_transfer.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/delete_disabled.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/shared.png
/var/lib/bamboo/tomcat/bamboo/images/icons/copy_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_indicator_blue.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/gear_ok.png
/var/lib/bamboo/tomcat/bamboo/images/icons/jira_status_unknown.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_cross.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/stop.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/bullet_notdone.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_blockexpanded.png
/var/lib/bamboo/tomcat/bamboo/images/icons/jira_type_unknown.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/help.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/gear_add.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/user_12.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_tick.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/panel.jpg
/var/lib/bamboo/tomcat/bamboo/images/icons/manual_grey.png
/var/lib/bamboo/tomcat/bamboo/images/icons/hr.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_first.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/gear_ok.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_right_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_folder.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/navigate_close.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_last_faded.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/serious_warning_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/add_10.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/next.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/fullscreen.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_lock.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/favicon.ico
/var/lib/bamboo/tomcat/bamboo/images/icons/bullet_blue.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/businessman.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/gear_forbidden.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/add_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/ajax-loader.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/star_off.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/ico_filters.png
/var/lib/bamboo/tomcat/bamboo/images/icons/comment_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/tools_20.png
/var/lib/bamboo/tomcat/bamboo/images/icons/warning_16.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/more.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_up_blue.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/arrow_down_blue.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/icon_spanner.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/favicon.png
/var/lib/bamboo/tomcat/bamboo/images/icons/last.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/jira_arrow_first.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/information.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/transparent.gif
/var/lib/bamboo/tomcat/bamboo/images/icons/bullet_red.gif
/var/lib/bamboo/tomcat/bamboo/images/build_status_top_left.gif
/var/lib/bamboo/tomcat/bamboo/images/index.gif
/var/lib/bamboo/tomcat/bamboo/images/rss.gif
/var/lib/bamboo/tomcat/bamboo/images/tab_submenu_on_right.gif
/var/lib/bamboo/tomcat/bamboo/images/build_successful.gif
/var/lib/bamboo/tomcat/bamboo/images/jquery-tablesorter/bg.gif
/var/lib/bamboo/tomcat/bamboo/images/jquery-tablesorter/asc.gif
/var/lib/bamboo/tomcat/bamboo/images/jquery-tablesorter/desc.gif
/var/lib/bamboo/tomcat/bamboo/images/next.gif
/var/lib/bamboo/tomcat/bamboo/images/signpost.gif
/var/lib/bamboo/tomcat/bamboo/images/bamboo-icon-64.png
/var/lib/bamboo/tomcat/bamboo/images/button-close.png
/var/lib/bamboo/tomcat/bamboo/images/display.png
/var/lib/bamboo/tomcat/bamboo/images/edit_build.gif
/var/lib/bamboo/tomcat/bamboo/images/permalink_dark_16.png
/var/lib/bamboo/tomcat/bamboo/images/contract.gif
/var/lib/bamboo/tomcat/bamboo/images/java.gif
/var/lib/bamboo/tomcat/bamboo/images/build_nav_arrow_last.gif
/var/lib/bamboo/tomcat/bamboo/images/build_results_fade.jpg
/var/lib/bamboo/tomcat/bamboo/images/screenshot_03.jpg
/var/lib/bamboo/tomcat/bamboo/images/blue_tab_left.gif
/var/lib/bamboo/tomcat/bamboo/images/success_rate_bg.gif
/var/lib/bamboo/tomcat/bamboo/images/messages.png
/var/lib/bamboo/tomcat/bamboo/images/icon_collapse_plus.gif
/var/lib/bamboo/tomcat/bamboo/images/tab_submenu_on_left.gif
/var/lib/bamboo/tomcat/bamboo/images/blue_tab_on_left.gif
/var/lib/bamboo/tomcat/bamboo/images/star_green.gif
/var/lib/bamboo/tomcat/bamboo/agent/agentMatchingRequirementsSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/agent/viewOfflineElasticAgentDetails.ftl
/var/lib/bamboo/tomcat/bamboo/agent/viewAgentExecutablePlans.ftl
/var/lib/bamboo/tomcat/bamboo/agent/viewAgents.ftl
/var/lib/bamboo/tomcat/bamboo/agent/viewAgent.ftl
/var/lib/bamboo/tomcat/bamboo/agent/imageMatchingRequirementsSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/agent/viewAgentCapabilities.ftl
/var/lib/bamboo/tomcat/bamboo/agent/commonAgentFunctions.ftl
/var/lib/bamboo/tomcat/bamboo/scripts/effects.js
/var/lib/bamboo/tomcat/bamboo/scripts/bamboo.js
/var/lib/bamboo/tomcat/bamboo/scripts/telemetry.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/jquery-ui-1.7.custom/index.html
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/plugins/namespace/namespace.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/plugins/namespace/namespace-min.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/plugins/bamboo/cronbuilder.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/plugins/bamboo/reload-image.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/plugins/bamboo/progressbar.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/jquery.cookie.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/jquery-ui-tabs-1.8.1.min.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/jquery-ui-droppable-1.8.2.min.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/jquery.tablesorter.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/addons/pager/icons/last.png
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/addons/pager/icons/next.png
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/addons/pager/icons/first.png
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/addons/pager/icons/prev.png
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/addons/pager/jquery.tablesorter.pager.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/addons/pager/jquery.tablesorter.pager.css
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/jquery.metadata.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/jquery.tablesorter.min.js
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/themes/basic/bg.gif
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/themes/basic/asc.gif
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/themes/basic/style.css
/var/lib/bamboo/tomcat/bamboo/scripts/jquery/tablesorter-2.0.3/themes/basic/desc.gif
/var/lib/bamboo/tomcat/bamboo/scripts/manual-stages.js
/var/lib/bamboo/tomcat/bamboo/scripts/build-decorator.js
/var/lib/bamboo/tomcat/bamboo/scripts/logs.js
/var/lib/bamboo/tomcat/bamboo/scripts/html5.js
/var/lib/bamboo/tomcat/bamboo/scripts/wforms.js
/var/lib/bamboo/tomcat/bamboo/scripts/tasks.js
/var/lib/bamboo/tomcat/bamboo/scripts/autocomplete-bamboo.js
/var/lib/bamboo/tomcat/bamboo/scripts/setup/jquery/readme.txt
/var/lib/bamboo/tomcat/bamboo/scripts/setup/jquery/jquery.js
/var/lib/bamboo/tomcat/bamboo/scripts/setup/jquery/jquery-min.js
/var/lib/bamboo/tomcat/bamboo/scripts/setup/bambooSetup.js
/var/lib/bamboo/tomcat/bamboo/scripts/setup/raphael/raphael-min.js
/var/lib/bamboo/tomcat/bamboo/scripts/setup/raphael/raphael.js
/var/lib/bamboo/tomcat/bamboo/scripts/setup/raphael/readme.txt
/var/lib/bamboo/tomcat/bamboo/scripts/aui-overrides.js
/var/lib/bamboo/tomcat/bamboo/scripts/jira-issues.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/effects.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/scriptaculous.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/slider.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/controls.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/dragdrop.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/builder.js
/var/lib/bamboo/tomcat/bamboo/scripts/scriptaculous/prototype.js
/var/lib/bamboo/tomcat/bamboo/scripts/progressbar.js
/var/lib/bamboo/tomcat/bamboo/scripts/labels.js
/var/lib/bamboo/tomcat/bamboo/scripts/prototype.js
/var/lib/bamboo/tomcat/bamboo/scripts/jira/inheritance.js
/var/lib/bamboo/tomcat/bamboo/scripts/jira/dropdown.js
/var/lib/bamboo/tomcat/bamboo/scripts/jira/autocomplete.js
/var/lib/bamboo/tomcat/bamboo/welcome.ftl
/var/lib/bamboo/tomcat/bamboo/error.ftl
/var/lib/bamboo/tomcat/bamboo/accessdenied.html
/var/lib/bamboo/tomcat/bamboo/login.ftl
/var/lib/bamboo/tomcat/bamboo/viewBuildFiles.ftl
/var/lib/bamboo/tomcat/bamboo/allPlansDashboard.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/antBuilderEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/maven2BuilderCapabilityEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/commandBuilderEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/maven2BuilderCapabilityView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/antBuilderView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/scriptBuilderEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/mavenBuilderEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/commandBuilderView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/scriptBuilderView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/builder/mavenBuilderView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/webRepository/noWebRepositoryView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/webRepository/noWebRepositorySummaryView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/webRepository/viewDefaultWebRepository.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/webRepository/editDefaultWebRepository.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/webRepository/defaultCommitView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/webRepository/defaultCommitSummaryView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/p4RepositoryView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/p4RepositoryMinimalEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/cvsRepositoryMinimalEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/p4RepositoryEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/cvsRepositoryView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/svnRepositoryView.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/p4RepositoryMavenPomCheckoutAccessEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/svnRepositoryMinimalEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/svnRepositoryEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/repository/cvsRepositoryEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/userRecipientEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/buildErrorNotificationEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/imRecipientEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/emailRecipientEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/buildQueueTimeoutEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/afterXFailedEdit.ftl
/var/lib/bamboo/tomcat/bamboo/templates/plugins/notifications/groupRecipientEdit.ftl
/var/lib/bamboo/tomcat/bamboo/styles/bamboo-widget.css
/var/lib/bamboo/tomcat/bamboo/styles/telemetry.css
/var/lib/bamboo/tomcat/bamboo/styles/logs.css
/var/lib/bamboo/tomcat/bamboo/styles/jquery-tablesorter-aui.css
/var/lib/bamboo/tomcat/bamboo/styles/buildChains.css
/var/lib/bamboo/tomcat/bamboo/styles/login.css
/var/lib/bamboo/tomcat/bamboo/styles/bamboo-ie.css
/var/lib/bamboo/tomcat/bamboo/styles/icons.css
/var/lib/bamboo/tomcat/bamboo/styles/gadgets/common.css
/var/lib/bamboo/tomcat/bamboo/styles/global-static.css
/var/lib/bamboo/tomcat/bamboo/styles/widePlanList.css
/var/lib/bamboo/tomcat/bamboo/styles/forms.css
/var/lib/bamboo/tomcat/bamboo/styles/labels.css
/var/lib/bamboo/tomcat/bamboo/styles/yui-support/img/ptr.gif
/var/lib/bamboo/tomcat/bamboo/styles/yui-support/img/round_4px_trans_gray.gif
/var/lib/bamboo/tomcat/bamboo/styles/yui-support/img/tab_right.gif
/var/lib/bamboo/tomcat/bamboo/styles/yui-support/img/tab_left.gif
/var/lib/bamboo/tomcat/bamboo/styles/yui-support/img/newcats_bkgd.gif
/var/lib/bamboo/tomcat/bamboo/styles/yui-support/img/loading.gif
/var/lib/bamboo/tomcat/bamboo/styles/tasks.css
/var/lib/bamboo/tomcat/bamboo/styles/buildResultsList.css
/var/lib/bamboo/tomcat/bamboo/styles/setup/aui-message-icon-sprite.png
/var/lib/bamboo/tomcat/bamboo/styles/setup/aui-3.3-forms.css
/var/lib/bamboo/tomcat/bamboo/styles/setup/aui-icon-forms.gif
/var/lib/bamboo/tomcat/bamboo/styles/setup/setup.css
/var/lib/bamboo/tomcat/bamboo/styles/setup/aui-3.3-forms-ie.css
/var/lib/bamboo/tomcat/bamboo/styles/setup/aui-3.3-messages.css
/var/lib/bamboo/tomcat/bamboo/styles/manual-stages.css
/var/lib/bamboo/tomcat/bamboo/styles/main2.css
/var/lib/bamboo/tomcat/bamboo/styles/main.css
/var/lib/bamboo/tomcat/bamboo/styles/tests.css
/var/lib/bamboo/tomcat/bamboo/styles/bamboo-status.css
/var/lib/bamboo/tomcat/bamboo/help/working-directory.ftl
/var/lib/bamboo/tomcat/bamboo/help/remote-api.ftl
/var/lib/bamboo/tomcat/bamboo/help/cvs-locks.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupSelectImport.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupWait.ftl
/var/lib/bamboo/tomcat/bamboo/setup/importFinished.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupDatabaseConnection.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupAdminUser.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupGeneralConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupDatabase.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupEmbeddedDbFailed.ftl
/var/lib/bamboo/tomcat/bamboo/setup/checklist.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupLicense.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupExpressError.ftl
/var/lib/bamboo/tomcat/bamboo/setup/setupCommon.ftl
/var/lib/bamboo/tomcat/bamboo/viewBuildHistory.ftl
/var/lib/bamboo/tomcat/bamboo/favicon.ico
/var/lib/bamboo/tomcat/bamboo/error/accessDenied.ftl
/var/lib/bamboo/tomcat/bamboo/error/error.ftl
/var/lib/bamboo/tomcat/bamboo/error/403-xml.ftl
/var/lib/bamboo/tomcat/bamboo/error/403.ftl
/var/lib/bamboo/tomcat/bamboo/error/403-json.ftl
/var/lib/bamboo/tomcat/bamboo/error/404.ftl
/var/lib/bamboo/tomcat/bamboo/error/500.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainRepository.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainPermissions.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/viewChainChangeHistory.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/configureChainVariables.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/delete.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/deleteStage.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainDependencies.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainDetails.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/changeChainNotification.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainConfigurationCommon.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainMiscellaneousOptions.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainStructure.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editStage.ftl
/var/lib/bamboo/tomcat/bamboo/chain/edit/editChainNotificationsSnippet.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/listChainResults.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewNotifications.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainSummary.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainArtifacts.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainLogs.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainFailurePeriods.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainActivityLog.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainResult.ftl
/var/lib/bamboo/tomcat/bamboo/chain/view/viewChainResultTestSummary.ftl
/var/lib/bamboo/tomcat/bamboo/chain/add/cloneJob.ftl
/var/lib/bamboo/tomcat/bamboo/chain/add/createJobTasks.ftl
/var/lib/bamboo/tomcat/bamboo/chain/add/createJob.ftl
/var/lib/bamboo/tomcat/bamboo/chain/add/addStage.ftl
/var/lib/bamboo/tomcat/bamboo/chain/add/jobCreationMethodSelection.ftl
/var/lib/bamboo/tomcat/bamboo/chain/config/viewChainConfiguration.ftl
/var/lib/bamboo/tomcat/bamboo/displayMyBuildSummaries.ftl
/var/lib/bamboo/tomcat/bamboo/jsExport.ftl
/var/lib/bamboo/tomcat/bamboo/template/inline/checkbox.ftl
/var/lib/bamboo/tomcat/bamboo/template/inline/controlheader.ftl
/var/lib/bamboo/tomcat/bamboo/template/inline/controlfooter.ftl
/var/lib/bamboo/tomcat/bamboo/template/inline/select.ftl
/var/lib/bamboo/tomcat/bamboo/template/inline/text.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/richtexteditor.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/datepicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/form.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/div.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/form-close.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/scripting-events.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/checkbox.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/debug.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/a-close.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/controlheader.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/controlfooter.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/password.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/optiontransferselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/fielderror.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/checkboxlist.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/pre.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/token.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/hidden.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/radio.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/submit.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/actionmessage.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/reset.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/file.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/doubleselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/textarea.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/combobox.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/head.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/select.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/updownselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/label.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/a.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/actionerror.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/div-close.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/text.ftl
/var/lib/bamboo/tomcat/bamboo/template/simple/radiomap.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/controlheader-core.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/richtexteditor.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/userPicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/datepicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/form.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/form-close.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/checkbox.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/debug.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/controlheader.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/controlfooter.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/password.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/optiontransferselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/checkboxlist.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/hidden.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/submit.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/controlfooter-core.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/tooltip.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/reset.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/file.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/doubleselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/textarea.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/periodPicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/combobox.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/styles.css
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/empty.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/head.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/select.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/updownselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/label.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/controlfooter-nodescription.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/actionerror.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/text.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/radiomap.ftl
/var/lib/bamboo/tomcat/bamboo/template/bambooCss/theme.properties
/var/lib/bamboo/tomcat/bamboo/template/aui/controlheader-core.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/richtexteditor.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/userPicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/datepicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/form.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/form-close.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/checkbox.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/debug.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/controlheader.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/controlfooter.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/password.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/optiontransferselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/checkboxlist.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/hidden.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/radio.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/submit.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/actionmessage.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/controlfooter-core.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/tooltip.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/reset.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/file.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/doubleselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/textarea.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/periodPicker.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/combobox.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/styles.css
/var/lib/bamboo/tomcat/bamboo/template/aui/empty.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/head.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/select.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/updownselect.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/label.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/controlfooter-nodescription.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/actionerror.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/text.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/radiomap.ftl
/var/lib/bamboo/tomcat/bamboo/template/aui/theme.properties
/var/lib/bamboo/tomcat/bamboo/decorators/admin.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/errorDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/setup.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/picker.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/userProfileDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/main.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/rest.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/planDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/resultDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/createWizardDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/help.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/configDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/login.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/tabbedContent.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/buildDecorator.ftl
/var/lib/bamboo/tomcat/bamboo/decorators/none.ftl
/var/lib/bamboo/tomcat/bamboo/legacyDashboard.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/urlrewrite.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/decorators.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-vcsversion-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-phpbuilder-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-language-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/joda-time-1.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/poi-scratchpad-3.5-FINAL.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/pjl-comp-filter-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/sal-spi-2.6.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-persistence-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/aws-java-sdk-1.1.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jasypt-1.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-codec-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-scripttask-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jcl-over-slf4j-1.5.8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xmlunit-1.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/backport-util-concurrent-2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/aspectjweaver-1.6.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xercesImpl-2.9.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/crowd-integration-api-2.3.0-rc2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/plexus-utils-1.5.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-provider-api-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-cli-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-file-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-ssh-external-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/cglib-nodep-2.1_3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-lang-2.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-upgrader-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jcaptcha-api-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xstream-1.3.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/webwork-2.2.7-atlassian-5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/activemq-pool-5.4.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-webresource-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xbean-spring-3.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/mina-core-2.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-artifact-manager-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-core-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-aop-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-classserver-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-monitor-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-logging-1.0.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/junit-4.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jcaptcha-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-core-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-velocity-0.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/howl-1.0.1-1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-compatibility-task-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jna-3.2.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/odmg-3.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/geronimo-transaction-2.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-model-2.1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-plugin-parameter-documenter-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-fileupload-1.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/servlet-api-2.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-beans-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/oscore-2.2.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-event-2.1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/crowd-integration-seraph25-2.3.0-rc2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-ant-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/osuser-1.0-20060106.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-elastic-server-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/urlrewrite-2.6.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jython-2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-web-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jtidy-4aug2000r7-dev.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-core-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-license-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-johnson-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/guava-8.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-trusted-apps-seraph-integration-2.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-reporting-api-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jaxb-impl-2.1.10.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/fontbox-1.2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/stax-api-1.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-jdbc-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-elastic-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/logkit-1.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/axis-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/activation-1.1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-project-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-branching-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xml-apis-1.3.03.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-testresultparser-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-tunnel-0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jempbox-1.2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-dbcp-1.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/slf4j-log4j12-1.5.8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-httpclient-3.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-trusted-apps-core-2.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-annotations-0.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/aspectjrt-1.6.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-user-1.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/annotations-6.0.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xapool-without-pool-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/bcprov-jdk15-1.44.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-spring-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/icu4j-3.8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jaxen-1.0-FCS.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xpp3_min-1.1.4c.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/sshd-core-0.5.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/ant-launcher-1.8.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/ldaptemplate-1.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/geronimo-jms_1.1_spec-1.1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-ip-2.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/saxpath-1.0-FCS.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/activeio-core-3.1.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wsdl4j-1.6.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-triggercondition-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-extras-2.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/doxia-sink-api-1.0-alpha-10.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-core-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-io-1.4-backport-IO-168.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/XmlSchema-1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/antlr-2.7.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-collections-3.2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-plugin-descriptor-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/applinks-spi-3.5.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/sitemesh-2.2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jcip-annotations-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-context-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/bamboo-maven-artifact-sharing-plugin-3.0-rc1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-git-1.5.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jsch-0.1.38.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-dao-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/winp-1.15-atlassian-1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xwork-1.2.5-atlassian-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/p4java-0.7.5-atlassian-8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/aopalliance-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/oro-2.0.8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/rome-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/velocity-tools-1.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/sal-api-2.6.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/smack-3.0.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/typica-1.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jcommon-1.0.12.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/axis-jaxrpc-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/hibernate-2.1.8-atlassian-9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jaxb-api-2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jsp-api-2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-discovery-0.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-profile-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/package-scanner-0.9.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-cache-api-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-mock-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-artifact-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/javacvs-atlassian-20080407.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-webdav-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/woodstox-core-asl-4.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-migration-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/mockobjects-alt-jdk1.3-j2ee1.3-0.09.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/activemq-protobuf-1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jencks-2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-grails-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-core-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-bootstrap-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-configuration-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/activemq-core-5.4.2-atlassian-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/svnkit-1.3.5.7539.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-repository-metadata-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-osgi-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/applinks-api-3.5.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-user-crowd-provider-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-http-lightweight-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/axis-saaj-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-plugin-registry-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/stax-api-1.0-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/hsqldb-1.8.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-support-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-webfragment-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/c3p0-0.9.1.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/lucene-core-2.3.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-buildnumberstamper-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/activemq-ra-5.4.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-web-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-pool-1.4-RC2-atlassian-1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-jelly-tags-regexp-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/stax2-api-3.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/ehcache-1.6.0-atlassian-3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-local-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/clover-3.1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-hibernate2-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xfire-core-1.2.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-labeller-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/freemarker-2.3.16-atlassian-5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/javassist-3.6.ga.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/org.tmatesoft.svnkit-trilead-ssh2-build213-svnkit-1.3-patch.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/fage-1.0-rc2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/imaging-01012005.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/msv-20020414.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/ognl-2.7.3-atlassian-3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-xwork-core-1.12.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bonnie-3.4.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-plugin-api-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/lucene-analyzers-2.3.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-fisheyecommitviewer-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/js-1.7R2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-config-0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jfreechart-1.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bucket-0.17.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-dotnet-3.2-rc1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-secure-random-2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/ant-1.8.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-cookie-tools-2.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/lingo-1.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/slide-webdavlib-2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-jms-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-servlet-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/geronimo-j2ee-connector_1.5_spec-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/xml-im-exporter-1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/log4j-1.2.15.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-settings-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-agent-remote-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/javarebel-sdk-1.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/antlr-runtime-3.1.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/pdfbox-1.2.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-jira-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/emma-2.0.4217.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-processutils-1.5-rc5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/applinks-host-3.5.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/velocity-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/kahadb-5.4.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/plexus-interactivity-api-1.0-alpha-4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-http-shared-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-seraph-2.5.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/staxmate-2.0.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/bndlib-0.0.255.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-core-4.5.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/slf4j-api-1.5.8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/dom4j-1.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/spring-remoting-2.0.7.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/plexus-container-default-1.0-alpha-9-stable-1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/exml-7.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/geronimo-connector-2.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jta-1.0.1B.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/isorelax-20020414.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-api-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-xwork-12-1.12.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jira-soapclient-4.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bandana-3.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-digester-1.8.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/multitenant-core-1.0-m14.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/embedded-crowd-api-2.3.0-rc2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-embedder-2.0.4-atlassian-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/com.trilead-trilead-ssh2-build213-svnkit-1.3-patch.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/crowd-integration-client-common-2.3.0-rc2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/stringtemplate-3.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jms-1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/propertyset-1.3-21Nov03.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/rife-continuations-0.0.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/regexp-1.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-mercurial-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/acegi-security-1.0.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/axis-wsdl4j-1.5.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-dbutils-1.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/quartz-1.6.5.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-maven-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jdom-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-php-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-jxpath-1.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-aws-0.30.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-mail-1.22.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/org.apache.felix.framework-3.0.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/jmock-1.0.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/geronimo-jta_1.1_spec-1.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/smackx-3.0.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-plugin-clover-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-ssh-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/sqljet-1.0.4.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/mail-1.4.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/relaxngDatatype-20020414.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-bamboo-charts-3.2.2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/truezip-6.6.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/commons-beanutils-1.8.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-profiling-1.8.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/crowd-integration-client-rest-2.3.0-rc2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/classworlds-1.1.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/bcmail-jdk15-1.44.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/sal-spring-2.6.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/maven-error-diagnostics-2.0.9.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-util-concurrent-2.0.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-plugins-osgi-events-2.8.0.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/atlassian-spring-1.3.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/poi-3.5-FINAL.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/lib/wagon-ssh-common-1.0-beta-2.jar
/var/lib/bamboo/tomcat/bamboo/WEB-INF/web.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/mimetypes.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextAgentServer.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/supportedDatabases.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/mail-config.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/database-defaults/oracle10and11g.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/database-defaults/hsqldb.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/database-defaults/mysql.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/database-defaults/postgresql.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/database-defaults/mssql.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/velocity.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextManagers.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContext.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextAcegiSecurity.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/rss-templates/ResultsOneLiner.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/rss-templates/ResultsHtmlSummary.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextLegacy.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextCaptcha.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextAcegiAuthorization.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/webwork.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextPlugin.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextUser.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/johnson-config.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextBootstrap.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/elastic-image-capabilities.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/validators.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/atlassian-user.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/crowd-ehcache.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextPersistence.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextBandana.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/upgrades.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/com/atlassian/plugin/metadata/application-provided-plugins.txt
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/com/atlassian/plugin/metadata/application-required-modules.txt
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/com/atlassian/plugin/metadata/application-required-plugins.txt
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/bamboo-init.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/log4j.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/seraph-paths.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/xwork.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/atlassian-bundled-plugins.zip
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/xwork-conversion.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/propertyset.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/crowd.properties
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/ChainCompletedIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/AfterXFailedHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/ChainCompletedHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/notificationCommonsHtml.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildQueueTimeoutTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildMissingCapableAgentHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/StageCompletedHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCompletedTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildQueueTimeoutIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildErrorIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/notificationCommonsText.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildHungIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildMissingCapableAgentIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCommentedHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildHungHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildQueueTimeoutHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildErrorTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/StageCompletedTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCompletedIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildMissingCapableAgentTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/StageCompletedIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/ChainCompletedTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCompletedHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildHungTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/AfterXFailedTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCommentedIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/ChainCompletedEmailSubject.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/AfterXFailedIm.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/notificationCommons.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/AfterXFailedEmailSubject.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCompletedEmailSubject.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildErrorHtmlEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/notification-templates/BuildCommentedTextEmail.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextChainManagers.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextScheduler.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/freemarker-lib/functions.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/freemarker-lib/ui.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/freemarker-lib/help.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/seraph-config.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/applicationContextMigration.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/freemarker_implicit.ftl
/var/lib/bamboo/tomcat/bamboo/WEB-INF/classes/ehcache.xml
/var/lib/bamboo/tomcat/bamboo/WEB-INF/sitemesh.xml
/var/lib/bamboo/tomcat/bamboo/textdownloads/buildLog.ftl
/var/lib/bamboo/tomcat/bamboo/author/viewAuthors.ftl
/var/lib/bamboo/tomcat/bamboo/author/viewAuthor.ftl
/var/lib/bamboo/tomcat/bamboo/author/authorReport.ftl
